POST http://localhost:8080/create-developer
Content-Type: application/json

{
  "developerLevel" : "JUNIOR",
  "developerSkillType" :  "BACK_END",
  "experienceYears" :  3,
  "memberID" :  "Mini",
  "name" :  "mouse Kim",
  "age":  "20"
}
